# Generated by Django 4.1.7 on 2023-02-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('VendorId', models.AutoField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('InventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('DateLog', models.DateTimeField()),
                ('CostItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.item')),
                ('VendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.vendors')),
            ],
        ),
    ]
